name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker compose build
        docker images | grep gichevaart
        docker save $(docker images | grep gichevaart | awk '{print $1":"$2}' | head -2) | gzip > gichevaart-images.tar.gz

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: nerdstips.com
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "gichevaart-images.tar.gz,docker-compose.yml"
        target: "/var/www/gichevaart"

    - name: Deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: nerdstips.com
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/gichevaart
          docker load < gichevaart-images.tar.gz
          docker compose down || true
          docker compose up -d
          rm gichevaart-images.tar.gz
          
          # Nginx is already configured in the nutritrack-web container