name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker compose build
        docker images | grep gichevaart
        docker save $(docker images | grep gichevaart | awk '{print $1":"$2}' | tr '\n' ' ') | gzip > gichevaart-images.tar.gz
        ls -lh gichevaart-images.tar.gz

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy files to server
      run: |
        scp -o StrictHostKeyChecking=no gichevaart-images.tar.gz docker-compose.yml root@nerdstips.com:/tmp/

    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no root@nerdstips.com << 'EOF'
          mkdir -p /var/www/gichevaart
          mv /tmp/docker-compose.yml /var/www/gichevaart/
          cd /var/www/gichevaart
          docker load < /tmp/gichevaart-images.tar.gz
          docker compose down || true
          docker compose up -d
          rm /tmp/gichevaart-images.tar.gz
          docker ps | grep gichevaart
        EOF