name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t gichevaart:latest .
        docker save gichevaart:latest | gzip > gichevaart.tar.gz

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.5
      with:
        host: nerdstips.com
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "gichevaart.tar.gz,docker-compose.yml"
        target: "/var/www/gichevaart"

    - name: Deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: nerdstips.com
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /var/www/gichevaart
          docker load < gichevaart.tar.gz
          docker-compose down
          docker-compose up -d
          rm gichevaart.tar.gz
          
          # Configure nginx if not already configured
          if [ ! -f /etc/nginx/sites-available/gichevaart ]; then
            cat > /etc/nginx/sites-available/gichevaart << 'EOF'
          server {
              listen 80;
              server_name gichevaart.com www.gichevaart.com;
              
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
          EOF
            ln -sf /etc/nginx/sites-available/gichevaart /etc/nginx/sites-enabled/
            nginx -t && systemctl reload nginx
          fi